$(document).ready(function(){
	$('#msm1').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm1'); 
	})
	$('#msm2').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm2'); 
	})
	$('#msm3').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm3'); 
	})
	$('#msm4').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm4'); 
	})
	$('#msm5').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm5'); 
	})
	$('#msm6').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm6'); 
	})
	$('#msm7').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm7'); 
	})
	$('#msm8').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm8'); 
	})
	$('#msm9').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@sm9'); 
	})
	$('#msm10').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@smA'); 
	})
	$('#msm11').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@smB'); 
	})
	$('#msm12').click(function(){ 
		$('#mess_pe').val($('#mess_pe').val()+'@smC'); 
	})
});